version: "2"

checks:
  file-lines:
    enabled: false
  method-lines:
    enabled: false
  method-complexity:
    enabled: false
  similar-code:
    enabled: false

exclude_patterns:
  - "**/*"
  - "**/.*"
  - "!packages/pkg-*/src/**"
  - "packages/pkg-app-shared/**"
