tasks:
  - name: chore
    init: >
      gp sync-await boot &&
      ./node_modules/.bin/playwright install-deps
    command: pnpm lint
  - name: dev server
    init: >
      nvm install 18 &&
      pnpm boot &&
      gp sync-done boot
      node scripts/local-services start &&
      node scripts/workspace.js set-gitpod-env
    command: >
      node scripts/local-services start &&
      pnpm dev

ports:
  - name: dev application
    port: 4000
    onOpen: notify
    visibility: public
  - name: dev ports
    port: 4900-4999
    onOpen: ignore
  - name: test ports
    port: 4800-4899
    onOpen: ignore
