image:
  file: docker/gitpod.Dockerfile

tasks:
  - init: pnpm boot && node scripts/local-services start && node scripts/workspace.js set-gitpod-env
    command: node scripts/local-services start && pnpm lint && pnpm dev

ports:
  - name: dev application
    port: 4000
    onOpen: notify
    visibility: public
  - name: dev ports
    port: 4900-4999
    onOpen: ignore
  - name: test ports
    port: 4800-4899
    onOpen: ignore
