version: 2.1

orbs:
  # Based on https://circleci.com/developer/orbs/orb/circleci/node
  node: circleci/node@5.0.3

jobs:
  test:
    machine:
      image: ubuntu-2204:current
      docker_layer_caching: true
    steps:
      - checkout
      - node/install:
          node-version: '18'
      - run:
          name: Install pnpm
          # Based on https://pnpm.io/continuous-integration#circleci
          command: curl -L https://pnpm.js.org/pnpm.js | node - add --global pnpm@7
      - run:
          name: Create cache key
          command: node ./scripts/workspace.mjs create-cache-key
      - restore_cache:
          name: Restore pnpm cache
          keys:
            - pnpm-packages-{{ checksum "workspace-cache-key.txt" }}
      - run:
          name: Install dependencies
          command: echo "$nrconf{restart} = 'a';" >> /etc/needrestart/needrestart.conf && pnpm boot-full
      - save_cache:
          name: Save pnpm cache
          key: pnpm-packages-{{ checksum "workspace-cache-key.txt" }}
          paths:
            - node_modules
      - run:
          name: Run tests
          command: pnpm test-full
      - store_test_results:
          path: ./build/test/reports/junit.xml
      - run:
          name: Send coverage report to Code Climate
          # Based on https://docs.codeclimate.com/docs/circle-ci-test-coverage-example
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
            ./cc-test-reporter format-coverage -t lcov -o ./build/test/reports/coverage/codeclimate.json ./build/test/reports/coverage/lcov.info
            ./cc-test-reporter upload-coverage -i ./build/test/reports/coverage/codeclimate.json
      - run:
          name: Audit dependencies
          command: pnpm audit --json

workflows:
  version: 2
  circleci-test:
    jobs:
      - test
