services:
  database:
    image: cockroachdb/cockroach:v22.1.8
    restart: always
    command: ['start-single-node', '--insecure']
    volumes:
      - database_volume:/cockroach/cockroach-data
    ports:
      - 4920:8080
      - 4922:26257

volumes:
  database_volume: {}
